-- ============================================================================
-- EunaTrack — migración inicial
-- Modelo: contenido compartido (areas → specialties → items) + progreso privado
-- por perfil (identificado por RUT, sesión anónima de Supabase).
--
-- FÓRMULA DE PROGRESO (fuente de verdad, ver .claude/skills/progress-model):
--   pct(item) = (studied + review1 + review2 + questions_done + cases_done) × 20
--   Cada dimensión aporta 20%. Los agregados por especialidad/área/global son
--   el PROMEDIO del pct de todos los ítems (los sin fila de progreso valen 0).
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- 1 · CONTENIDO (compartido, solo lectura para usuarios)
-- ────────────────────────────────────────────────────────────────────────────

create table public.areas (
  id integer generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0
);

create table public.specialties (
  id integer generated by default as identity primary key,
  area_id integer not null references public.areas(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  unique (area_id, name)
);
create index specialties_area_idx on public.specialties(area_id);

create type public.item_type as enum ('tema', 'examen_complementario');

create table public.items (
  id integer generated by default as identity primary key,
  specialty_id integer not null references public.specialties(id) on delete cascade,
  title text not null,
  item_type public.item_type not null default 'tema',
  sort_order integer not null default 0,
  priority integer,
  unique (specialty_id, title)
);
create index items_specialty_idx on public.items(specialty_id);

-- Matriz de exigencia del internado (9 ejes del programa original).
-- Modelado como flags: los 9 ejes son fijos en el programa; una tabla
-- normalizada `dimensions` agregaría joins sin beneficio real. Si el programa
-- cambiara de ejes, se agrega columna con `alter table` (cambio de datos, no
-- de código de UI: los chips se derivan de este registro).
create table public.item_requirements (
  item_id integer primary key references public.items(id) on delete cascade,
  fisiopatologia boolean not null default false,
  conocimiento_general boolean not null default false,
  dx_sospecha boolean not null default false,
  dx_especifico boolean not null default false,
  tto_inicial boolean not null default false,
  tto_completo boolean not null default false,
  estudio_complicaciones boolean not null default false,
  seguimiento_derivar boolean not null default false,
  seguimiento_cronico boolean not null default false
);

-- Catálogo oficial del Perfil EUNACOM 2026 v3 (1.557 códigos, 7 áreas).
-- Estructura del código: area.especialidad.seccion.correlativo
--   secciones 1/2 (situaciones clínicas): usan dx/tto/followup
--   sección 3 (conocimientos generales): sin niveles
--   secciones 4/5 (exámenes, procedimientos): usan extra_level
create table public.eunacom_codes (
  code text primary key,
  official_title text not null,
  area text not null,
  specialty text not null,
  section text,
  dx_level text,
  tto_level text,
  followup_level text,
  extra_level text
);

-- Mapeo N:N ítem del internado ↔ código(s) EUNACOM. Editable a futuro.
-- confidence: 'confirmed' (revisado por humano) | 'suggested' (mapeo semántico
-- automático pendiente de revisión).
create table public.item_eunacom_map (
  item_id integer not null references public.items(id) on delete cascade,
  eunacom_code text not null references public.eunacom_codes(code) on delete cascade,
  confidence text not null default 'suggested'
    check (confidence in ('confirmed', 'suggested')),
  primary key (item_id, eunacom_code)
);

-- ────────────────────────────────────────────────────────────────────────────
-- 2 · USUARIOS Y PROGRESO (privado por perfil)
--
-- Enfoque de identidad elegido (documentado también en README):
--   · El dispositivo inicia una sesión ANÓNIMA de Supabase (auth.users).
--   · login_with_rut() (SECURITY DEFINER) valida el DV, hace upsert del
--     profile y vincula auth.uid() ↔ profile en profile_auth_links.
--   · Varias sesiones anónimas (teléfono, tablet, PC) pueden apuntar al mismo
--     profile → sincronización entre dispositivos.
--   · RLS usa current_profile_id() para aislar los datos de cada perfil.
-- LIMITACIÓN CONOCIDA: no hay contraseña; cualquiera que conozca un RUT
-- válido puede entrar a ese perfil. Aceptado para el MVP y advertido en README.
-- ────────────────────────────────────────────────────────────────────────────

create table public.profiles (
  id uuid primary key default gen_random_uuid(),
  rut text not null unique
    check (rut ~ '^[0-9]{7,8}-[0-9K]$'),  -- normalizado: sin puntos, DV mayúscula
  created_at timestamptz not null default now(),
  settings jsonb not null default '{"items_per_day": 5, "theme": "system"}'::jsonb
);

create table public.profile_auth_links (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);
create index profile_auth_links_profile_idx on public.profile_auth_links(profile_id);

create table public.item_progress (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  item_id integer not null references public.items(id) on delete cascade,
  -- 5 dimensiones de la fórmula de progreso (20% cada una)
  studied boolean not null default false,
  review1 boolean not null default false,
  review2 boolean not null default false,
  questions_done boolean not null default false,  -- bool (no int): coincide con el toggle del diseño
  cases_done boolean not null default false,
  -- metadatos de estudio
  mastery smallint check (mastery between 1 and 5),
  last_studied_at date,
  next_review_at date,
  notes text not null default '',
  updated_at timestamptz not null default now(),
  primary key (profile_id, item_id)
);
create index item_progress_item_idx on public.item_progress(item_id);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

create trigger item_progress_touch
  before update on public.item_progress
  for each row execute function public.touch_updated_at();

-- ────────────────────────────────────────────────────────────────────────────
-- 3 · IDENTIDAD: helpers y RPC de login por RUT
-- ────────────────────────────────────────────────────────────────────────────

-- Perfil asociado a la sesión actual (o null).
create or replace function public.current_profile_id()
returns uuid
language sql stable security definer
set search_path = public
as $$
  select profile_id from public.profile_auth_links
  where auth_user_id = auth.uid()
$$;

-- Validación del dígito verificador chileno (módulo 11).
-- Espera el RUT ya normalizado: solo dígitos + DV, sin puntos, con guion.
create or replace function public.is_valid_rut(p_rut text)
returns boolean
language plpgsql immutable
as $$
declare
  v_body text;
  v_dv text;
  v_sum integer := 0;
  v_factor integer := 2;
  v_expected text;
  v_mod integer;
begin
  if p_rut !~ '^[0-9]{7,8}-[0-9K]$' then
    return false;
  end if;
  v_body := split_part(p_rut, '-', 1);
  v_dv := split_part(p_rut, '-', 2);
  for i in reverse length(v_body)..1 loop
    v_sum := v_sum + (substr(v_body, i, 1))::integer * v_factor;
    v_factor := case when v_factor = 7 then 2 else v_factor + 1 end;
  end loop;
  v_mod := 11 - (v_sum % 11);
  v_expected := case v_mod when 11 then '0' when 10 then 'K' else v_mod::text end;
  return v_dv = v_expected;
end $$;

-- Login: upsert de profile por RUT + vínculo con la sesión anónima actual.
create or replace function public.login_with_rut(p_rut text)
returns public.profiles
language plpgsql security definer
set search_path = public
as $$
declare
  v_rut text;
  v_profile public.profiles;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED: inicia una sesión (anónima) antes de login_with_rut';
  end if;

  -- normalizar: quitar puntos/espacios, DV a mayúscula, asegurar guion
  v_rut := upper(regexp_replace(p_rut, '[^0-9kK]', '', 'g'));
  if length(v_rut) < 2 then
    raise exception 'INVALID_RUT';
  end if;
  v_rut := left(v_rut, length(v_rut) - 1) || '-' || right(v_rut, 1);

  if not public.is_valid_rut(v_rut) then
    raise exception 'INVALID_RUT: dígito verificador incorrecto';
  end if;

  insert into public.profiles (rut) values (v_rut)
  on conflict (rut) do update set rut = excluded.rut
  returning * into v_profile;

  insert into public.profile_auth_links (auth_user_id, profile_id)
  values (auth.uid(), v_profile.id)
  on conflict (auth_user_id) do update set profile_id = excluded.profile_id;

  return v_profile;
end $$;

revoke all on function public.login_with_rut(text) from public;
grant execute on function public.login_with_rut(text) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────
-- 4 · PROGRESO: fórmula y agregados (vistas con security_invoker → RLS aplica)
-- ────────────────────────────────────────────────────────────────────────────

-- pct de un registro de progreso: 5 dimensiones × 20.
create or replace function public.progress_pct(p public.item_progress)
returns integer
language sql immutable
as $$
  select (p.studied::int + p.review1::int + p.review2::int
        + p.questions_done::int + p.cases_done::int) * 20
$$;

-- pct por ítem del perfil actual (ítems sin fila = 0).
create or replace view public.v_item_progress_pct
with (security_invoker = true) as
select
  i.id as item_id,
  i.specialty_id,
  coalesce(public.progress_pct(ip), 0) as pct
from public.items i
left join public.item_progress ip
  on ip.item_id = i.id and ip.profile_id = public.current_profile_id();

-- agregado por especialidad del perfil actual.
create or replace view public.v_specialty_progress
with (security_invoker = true) as
select
  s.id as specialty_id,
  s.area_id,
  s.name,
  count(v.item_id) as items_total,
  count(*) filter (where v.pct = 100) as items_done,
  coalesce(round(avg(v.pct), 1), 0) as pct
from public.specialties s
left join public.v_item_progress_pct v on v.specialty_id = s.id
group by s.id;

-- agregado por área del perfil actual.
create or replace view public.v_area_progress
with (security_invoker = true) as
select
  a.id as area_id,
  a.name,
  count(v.item_id) as items_total,
  count(*) filter (where v.pct = 100) as items_done,
  coalesce(round(avg(v.pct), 1), 0) as pct
from public.areas a
left join public.specialties s on s.area_id = a.id
left join public.v_item_progress_pct v on v.specialty_id = s.id
group by a.id;

-- ────────────────────────────────────────────────────────────────────────────
-- 5 · ROW LEVEL SECURITY
-- ────────────────────────────────────────────────────────────────────────────

alter table public.areas enable row level security;
alter table public.specialties enable row level security;
alter table public.items enable row level security;
alter table public.item_requirements enable row level security;
alter table public.eunacom_codes enable row level security;
alter table public.item_eunacom_map enable row level security;
alter table public.profiles enable row level security;
alter table public.profile_auth_links enable row level security;
alter table public.item_progress enable row level security;

-- contenido: lectura para cualquier sesión autenticada (incl. anónima)
create policy "content read" on public.areas
  for select to authenticated using (true);
create policy "content read" on public.specialties
  for select to authenticated using (true);
create policy "content read" on public.items
  for select to authenticated using (true);
create policy "content read" on public.item_requirements
  for select to authenticated using (true);
create policy "content read" on public.eunacom_codes
  for select to authenticated using (true);
create policy "content read" on public.item_eunacom_map
  for select to authenticated using (true);

-- perfil propio: leer y actualizar (crear solo vía login_with_rut)
create policy "own profile read" on public.profiles
  for select to authenticated using (id = public.current_profile_id());
create policy "own profile update" on public.profiles
  for update to authenticated
  using (id = public.current_profile_id())
  with check (id = public.current_profile_id());

-- vínculos: solo ver el propio (escritura solo vía login_with_rut)
create policy "own link read" on public.profile_auth_links
  for select to authenticated using (auth_user_id = auth.uid());

-- progreso: CRUD solo sobre el perfil propio
create policy "own progress select" on public.item_progress
  for select to authenticated using (profile_id = public.current_profile_id());
create policy "own progress insert" on public.item_progress
  for insert to authenticated with check (profile_id = public.current_profile_id());
create policy "own progress update" on public.item_progress
  for update to authenticated
  using (profile_id = public.current_profile_id())
  with check (profile_id = public.current_profile_id());
create policy "own progress delete" on public.item_progress
  for delete to authenticated using (profile_id = public.current_profile_id());
