-- ============================================================================
-- EunaTrack — nivel intermedio "tema" entre specialties e items
-- Agrega la tabla `topics` y la FK `items.topic_id` para que el Panel pueda
-- renderizar Especialidad → Tema → Ítem en vez del actual plano
-- Especialidad → Ítem. Cambio puramente ADITIVO: no toca vistas, funciones ni
-- el resto del esquema de 0001_init.sql; `topic_id` solo agrupa para la UI.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- 1 · TEMAS (subcapítulos dentro de una especialidad, solo lectura)
-- ────────────────────────────────────────────────────────────────────────────

create table public.topics (
  id integer generated by default as identity primary key,
  specialty_id integer not null references public.specialties(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  unique (specialty_id, name)
);
create index topics_specialty_idx on public.topics(specialty_id);

-- ────────────────────────────────────────────────────────────────────────────
-- 2 · VÍNCULO ítem → tema
-- ────────────────────────────────────────────────────────────────────────────

-- topic_id es NULLABLE a propósito: la agrupación clínica de los ítems en
-- subcapítulos es trabajo de contenido que va por detrás del esquema. Un ítem
-- debe seguir visible bajo su especialidad (items.specialty_id) aunque todavía
-- no tenga tema asignado. La cobertura total de temas se valida en el pipeline
-- de contenido (el propio generador de seed), no con una constraint: la DB
-- queda permisiva para contenido futuro que quizá nunca tenga capa de temas.
-- on delete set null: borrar un tema no debe borrar sus ítems, solo desagrupar.
alter table public.items
  add column topic_id integer references public.topics(id) on delete set null;
create index items_topic_idx on public.items(topic_id);

-- Nota de diseño (decisión deliberada, no un olvido):
--   · items.specialty_id NO se elimina ni se normaliza aunque topics.specialty_id
--     ya implique la especialidad del ítem de forma transitiva. specialty_id
--     sigue siendo la FK portante: la leen directo las vistas de 0001_init.sql
--     (v_item_progress_pct / v_specialty_progress / v_area_progress) y el
--     frontend, y ninguno debe cambiar por esta migración.
--   · No hay trigger que fuerce topics.specialty_id = items.specialty_id para un
--     item.topic_id dado. topics e items son contenido gestionado por pipeline
--     (RLS solo concede select, nunca escritura de cliente): la consistencia la
--     garantiza estructuralmente el generador de seed (un ítem solo recibe el
--     topic_id del tema en el que está anidado en la fuente), no una constraint.
--     Proporcionado para datos de contenido solo-lectura.

-- ────────────────────────────────────────────────────────────────────────────
-- 3 · ROW LEVEL SECURITY
-- ────────────────────────────────────────────────────────────────────────────

alter table public.topics enable row level security;

-- contenido: lectura para cualquier sesión autenticada (incl. anónima)
create policy "content read" on public.topics
  for select to authenticated using (true);
